In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

from sklearn.metrics import accuracy_score
import requests, zipfile, io
import os, glob
import random
import shutil


print(tf.__version__)
tf.keras.mixed_precision.set_global_policy('mixed_float16')

2.9.1
INFO:tensorflow:Mixed precision compatibility check (mixed_float16): OK
Your GPU will likely run quickly with dtype policy mixed_float16 as it has compute capability of at least 7.0. Your GPU: NVIDIA GeForce RTX 2070 SUPER, compute capability 7.5


In [7]:
# Define input sentences
sentences = [
    'i love my dog',
    'I, love my cat'
    ]

# Initialize the Tokenizer class
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words = 100)

# Generate indices for each word in the corpus
tokenizer.fit_on_texts(sentences)

# Get the indices and print it
word_index = tokenizer.word_index
print(word_index)

{'i': 1, 'love': 2, 'my': 3, 'dog': 4, 'cat': 5}


In [6]:
# Define input sentences
sentences = [
    'i love my dog',
    'I, love my cat',
    'You love my dog!'
]

# Initialize the Tokenizer class
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words = 4)

# Generate indices for each word in the corpus
tokenizer.fit_on_texts(sentences)

# Get the indices and print it
word_index = tokenizer.word_index
print(word_index)

{'love': 1, 'my': 2, 'i': 3, 'dog': 4, 'cat': 5, 'you': 6}


In [9]:
sentences = [
    'I love my dog',
    'my dog loves my manatee',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is amazing?',
]

# Initialize the Tokenizer class
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words = 100, oov_token="<OOV>")

# Tokenize the input sentences
tokenizer.fit_on_texts(sentences)

# Get the word index dictionary
word_index = tokenizer.word_index

# Generate list of token sequences
sequences = tokenizer.texts_to_sequences(sentences)

padded = tf.keras.preprocessing.sequence.pad_sequences(sequences, maxlen=5)


# Print the result
print("\nWord Index = \n" , word_index)
print("\nSequences = \n" , sequences)
print("\nPadded Sequences:\n", padded)


Word Index = 
 {'<OOV>': 1, 'my': 2, 'dog': 3, 'love': 4, 'i': 5, 'you': 6, 'loves': 7, 'manatee': 8, 'cat': 9, 'do': 10, 'think': 11, 'is': 12, 'amazing': 13}

Sequences = 
 [[5, 4, 2, 3], [2, 3, 7, 2, 8], [5, 4, 2, 9], [6, 4, 2, 3], [10, 6, 11, 2, 3, 12, 13]]

Padded Sequences:
 [[ 0  5  4  2  3]
 [ 2  3  7  2  8]
 [ 0  5  4  2  9]
 [ 0  6  4  2  3]
 [11  2  3 12 13]]


In [11]:
# Try with words that the tokenizer wasn't fit to
test_data = [
    'i really love my dog',
    'my dog loves my manatee'
]

# Generate the sequences
test_seq = tokenizer.texts_to_sequences(test_data)

# Print the word index dictionary
print("\nWord Index = " , word_index)

# Print the sequences with OOV
print("\nTest Sequence = ", test_seq)

# Print the padded result
padded = tf.keras.preprocessing.sequence.pad_sequences(test_seq, maxlen=10)
print("\nPadded Test Sequence: ")
print(padded)


Word Index =  {'<OOV>': 1, 'my': 2, 'dog': 3, 'love': 4, 'i': 5, 'you': 6, 'loves': 7, 'manatee': 8, 'cat': 9, 'do': 10, 'think': 11, 'is': 12, 'amazing': 13}

Test Sequence =  [[5, 1, 4, 2, 3], [2, 3, 7, 2, 8]]

Padded Test Sequence: 
[[0 0 0 0 0 5 1 4 2 3]
 [0 0 0 0 0 2 3 7 2 8]]
